[ids]

*

# Include the shipped Swedish layout
# include layouts/se

# [global]
# default_layout = se

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

